module Lab2
( Student
, name
, surname
, sex
, day
, month
, year
, group
, iq
, students
, french
, discrete_mathematics
, programming
) where

data Student = St {name, surname :: String, sex :: Char, day, month, year :: Int, group :: Int, iq :: Int} deriving (Show, Read)

students = [
  St {name="Maksim", surname="Churkin", sex='m', day=13, month=12, year=1991, group=331, iq=100},
  St {name="Vera", surname="Aminova", sex='f', day=1, month=6, year=1991, group=331, iq=115},
  St {name="Elizaveta", surname="Anohina", sex='f', day=27, month=2, year=1992, group=332, iq=105},
  St {name="Dar'ja", surname="Grekova", sex='f', day=18, month=3, year=1992, group=333, iq=106},
  St {name="Ivan", surname="Demkovich", sex='m', day=3, month=1, year=1993, group=331, iq=107},
  St {name="Denis", surname="Dublenyh", sex='m', day=6, month=4, year=1991, group=334, iq=106},
  St {name="Aleksej", surname="Korolev", sex='m', day=24, month=5, year=1993, group=333, iq=114},
  St {name="Vjacheslav", surname="Shaprynskij", sex='m', day=28, month=11, year=1992, group=334, iq=103},
  St {name="Vladislav", surname="Isenbaev", sex='m', day=11, month=10, year=1991, group=331, iq=103},
  St {name="Dmitrij", surname="Zonin", sex='m', day=10, month=4, year=1991, group=332, iq=108},
  St {name="Dmitrij", surname="Karpov", sex='m', day=9, month=8, year=1991, group=331, iq=108},
  St {name="Aleksandr", surname="Golubev", sex='m', day=19, month=9, year=1992, group=332, iq=106},
  St {name="Vadim", surname="Shakuro", sex='m', day=5, month=1, year=1992, group=333, iq=108},
  St {name="Sergej", surname="Larjushkin", sex='m', day=9, month=3, year=1993, group=333, iq=107},
  St {name="Aleksandr", surname="Suhman", sex='m', day=20, month=2, year=1993, group=331, iq=115},
  St {name="Kirill", surname="Kornjuhin", sex='m', day=30, month=12, year=1992, group=332, iq=106},
  St {name="Marina", surname="Maslennikova", sex='f', day=29, month=3, year=1990, group=332, iq=114},
  St {name="Anton", surname="Putrik", sex='m', day=2, month=11, year=1991, group=331, iq=107},
  St {name="Maksim", surname="Putrik", sex='m', day=16, month=10, year=1991, group=332, iq=107},
  St {name="Aleksandr", surname="Chegodaev", sex='m', day=12, month=9, year=1993, group=332, iq=105},
  St {name="Viktor", surname="Samun'", sex='m', day=19, month=7, year=1992, group=331, iq=108},
  St {name="Dmitrij", surname="Korolev", sex='m', day=22, month=6, year=1991, group=333, iq=106},
  St {name="Pavel", surname="Skripnichenko", sex='m', day=11, month=5, year=1991, group=331, iq=115},
  St {name="Aleksandr", surname="Toporov", sex='m', day=4, month=11, year=1991, group=334, iq=102},
  St {name="Elena", surname="Shalashugina", sex='f', day=5, month=12, year=1992, group=331, iq=105},
  St {name="Denis", surname="Jadarinkin", sex='m', day=17, month=8, year=1992, group=331, iq=103},
  St {name="Daniil", surname="Ajzenshtejn", sex='m', day=15, month=5, year=1993, group=331, iq=105},
  St {name="Vera", surname="Aminova", sex='f', day=26, month=4, year=1993, group=332, iq=106},
  St {name="Ksenija", surname="Afonenko", sex='f', day=18, month=3, year=1993, group=332, iq=103},
  St {name="Il'ja", surname="Degtjarev", sex='m', day=28, month=2, year=1992, group=333, iq=106},
  St {name="Dmitrij", surname="Zonin", sex='m', day=22, month=1, year=1992, group=331, iq=106},
  St {name="Marija", surname="Kolmogorova", sex='f', day=21, month=9, year=1991, group=333, iq=103},
  St {name="Viktor", surname="Samun'", sex='m', day=7, month=7, year=1992, group=331, iq=109},
  St {name="Oleg", surname="Mihajlov", sex='m', day=6, month=11, year=1992, group=331, iq=107},
  St {name="Grigorij", surname="Semenov", sex='m', day=14, month=10, year=1989, group=334, iq=102},
  St {name="Ivan", surname="Kadochnikov", sex='m', day=22, month=7, year=1993, group=334, iq=103},
  St {name="Aleksej", surname="Korolev", sex='m', day=15, month=6, year=1991, group=331, iq=102},
  St {name="Aleksej", surname="Kutyrev", sex='m', day=1, month=5, year=1991, group=331, iq=111},
  St {name="Elena", surname="Lysenko", sex='f', day=28, month=1, year=1990, group=333, iq=107},
  St {name="Anton", surname="Putrik", sex='m', day=23, month=11, year=1992, group=333, iq=107},
  St {name="Il'ja", surname="Otradnikov", sex='m', day=15, month=3, year=1992, group=331, iq=115},
  St {name="Anna", surname="Ustavshhikova", sex='f', day=10, month=2, year=1991, group=334, iq=100},
  St {name="Boris", surname="Safronov", sex='m', day=20, month=8, year=1993, group=334, iq=105},
  St {name="Nadezhda", surname="Skachkova", sex='f', day=1, month=12, year=1991, group=331, iq=111},
  St {name="Vladimir", surname="Telichkin", sex='m', day=8, month=7, year=1991, group=331, iq=114},
  St {name="Ivan", surname="Turmyshev", sex='m', day=7, month=5, year=1992, group=332, iq=107},
  St {name="Evgenij", surname="Kuznecov", sex='m', day=4, month=11, year=1992, group=331, iq=108},
  St {name="Sergej", surname="Zajkov", sex='m', day=3, month=8, year=1991, group=331, iq=108},
  St {name="Julija", surname="Burkova", sex='f', day=13, month=3, year=1991, group=331, iq=109},
  St {name="Jurij", surname="Starovojtov", sex='m', day=12, month=4, year=1993, group=334, iq=102},
  St {name="Jakov", surname="Mozgoev", sex='m', day=10, month=9, year=1991, group=332, iq=107},
  St {name="Elena", surname="Mihajlova", sex='f', day=27, month=12, year=1993, group=334, iq=111},
  St {name="Egor", surname="Ignat'ev", sex='m', day=26, month=9, year=1992, group=333, iq=107},
  St {name="Sergej", surname="Toropkin", sex='m', day=21, month=4, year=1991, group=331, iq=101},
  St {name="Tat'jana", surname="Eliseeva", sex='f', day=25, month=6, year=1991, group=333, iq=100},
  St {name="Adel'", surname="Auhatova", sex='f', day=12, month=3, year=1991, group=332, iq=105},
  St {name="Aleksej", surname="Efremov", sex='m', day=19, month=2, year=1993, group=334, iq=105},
  St {name="Diana", surname="Taratuhina", sex='f', day=17, month=1, year=1992, group=334, iq=102},
  St {name="Rostislav", surname="Devjatov", sex='m', day=5, month=8, year=1992, group=334, iq=108},
  St {name="Anton", surname="Vasil'ev", sex='m', day=2, month=5, year=1991, group=332, iq=112},
  St {name="Anton", surname="Mahlin", sex='m', day=8, month=4, year=1990, group=332, iq=109},
  St {name="Elena", surname="Tret'jak", sex='f', day=16, month=3, year=1993, group=333, iq=105},
  St {name="Igor'", surname="Gulamov", sex='m', day=25, month=6, year=1991, group=333, iq=105},
  St {name="Boris", surname="Perel'man", sex='m', day=13, month=3, year=1992, group=332, iq=115},
  St {name="Il'ja", surname="Kornakov", sex='m', day=22, month=12, year=1992, group=333, iq=101},
  St {name="Vladimir", surname="Bataev", sex='m', day=10, month=10, year=1991, group=334, iq=102},
  St {name="Arsenij", surname="Klimovskij", sex='m', day=4, month=5, year=1991, group=331, iq=102},
  St {name="Fedor", surname="Pahomov", sex='m', day=17, month=3, year=1993, group=334, iq=107},
  St {name="Viktor", surname="Aljushin", sex='m', day=10, month=12, year=1993, group=334, iq=101},
  St {name="Igor'", surname="Mahlin", sex='m', day=28, month=1, year=1992, group=332, iq=108},
  St {name="Ivan", surname="Kozlov", sex='m', day=21, month=8, year=1991, group=332, iq=111},
  St {name="Vadim", surname="Avdeev", sex='m', day=11, month=3, year=1992, group=333, iq=111},
  St {name="Anton", surname="Fonarev", sex='m', day=3, month=9, year=1991, group=332, iq=107},
  St {name="Andrej", surname="Kolosov", sex='m', day=1, month=7, year=1991, group=332, iq=107},
  St {name="Marina", surname="Stepanova", sex='f', day=9, month=11, year=1992, group=334, iq=104},
  St {name="Matvej", surname="Kornilov", sex='m', day=7, month=10, year=1993, group=334, iq=105},
  St {name="Jakov", surname="Dlugach", sex='m', day=5, month=5, year=1991, group=333, iq=109},
  St {name="Igor'", surname="Turkin", sex='m', day=4, month=5, year=1991, group=333, iq=109},
  St {name="Oleg", surname="Samojlenko", sex='m', day=1, month=8, year=1992, group=332, iq=107},
  St {name="Ekaterina", surname="Sambukova", sex='f', day=15, month=3, year=1993, group=334, iq=104},
  St {name="Dmitrij", surname="Alekseev", sex='m', day=25, month=2, year=1992, group=334, iq=104},
  St {name="Pavel", surname="Jushhenko", sex='m', day=21, month=10, year=1990, group=334, iq=108},
  St {name="Ivan", surname="Dudinov", sex='m', day=22, month=12, year=1991, group=331, iq=108},
  St {name="Viktor", surname="Chernyshov", sex='m', day=16, month=4, year=1991, group=331, iq=99},
  St {name="Anton", surname="Lupanov", sex='m', day=11, month=12, year=1993, group=333, iq=108},
  St {name="Ivan", surname="Puzyrevskij", sex='m', day=6, month=1, year=1991, group=333, iq=99},
  St {name="Aleksandr", surname="Petrov", sex='m', day=20, month=1, year=1992, group=332, iq=107},
  St {name="Leonid", surname="Andrievskij", sex='m', day=17, month=7, year=1990, group=334, iq=107},
  St {name="Aleksandr", surname="Roshhupkin", sex='m', day=1, month=3, year=1991, group=333, iq=98},
  St {name="Aleksandr", surname="Korchagin", sex='m', day=15, month=7, year=1991, group=334, iq=112},
  St {name="Kirill", surname="Zhalnin", sex='m', day=10, month=8, year=1992, group=332, iq=104},
  St {name="Dmitrij", surname="Gorbik", sex='m', day=13, month=6, year=1991, group=332, iq=104},
  St {name="Anton", surname="Bobkov", sex='m', day=27, month=2, year=1991, group=333, iq=104},
  St {name="Konstantin", surname="Novikov", sex='m', day=22, month=10, year=1993, group=332, iq=101},
  St {name="Vladimir", surname="Tkachev", sex='m', day=21, month=1, year=1992, group=334, iq=94},
  St {name="Ivan", surname="Kondrashov", sex='m', day=6, month=5, year=1994, group=331, iq=104},
  St {name="Danila", surname="Potapov", sex='m', day=23, month=6, year=1991, group=332, iq=104},
  St {name="Boris", surname="Agafoncev", sex='m', day=13, month=4, year=1993, group=334, iq=135},
  St {name="Aleksej", surname="Davydov", sex='m', day=7, month=7, year=1993, group=333, iq=103},
  St {name="Denis", surname="Lisov", sex='m', day=4, month=12, year=1990, group=333, iq=108},
  St {name="Ivan", surname="Bogatyj", sex='m', day=14, month=4, year=1991, group=333, iq=107},
  St {name="Marija", surname="Felicina", sex='f', day=18, month=2, year=1990, group=333, iq=104},
  St {name="Andrej", surname="Vikulov", sex='m', day=2, month=2, year=1993, group=332, iq=107},
  St {name="Aleksej", surname="Kricin", sex='m', day=22, month=12, year=1991, group=332, iq=107},
  St {name="Artem", surname="Kuharenko", sex='m', day=26, month=7, year=1990, group=332, iq=103},
  St {name="Sergej", surname="Anohovskij", sex='m', day=30, month=4, year=1993, group=331, iq=103},
  St {name="Aleksandr", surname="Zaharov", sex='m', day=29, month=12, year=1991, group=332, iq=103},
  St {name="Andrej", surname="Kotov", sex='m', day=28, month=10, year=1991, group=333, iq=111},
  St {name="Kirill", surname="Znamenskij", sex='m', day=30, month=9, year=1993, group=334, iq=103},
  St {name="Vladimir", surname="Lesnichenko", sex='m', day=31, month=8, year=1993, group=334, iq=103},
  St {name="Il'ja", surname="Smirnov", sex='m', day=31, month=7, year=1991, group=331, iq=108},
  St {name="Aleksandr", surname="Kolesnikov", sex='m', day=31, month=3, year=1991, group=334, iq=101},
  St {name="Nikolaj", surname="Pechenkin", sex='m', day=13, month=11, year=1991, group=333, iq=115},
  St {name="Ignat", surname="Kolesnichenko", sex='m', day=29, month=7, year=1990, group=332, iq=101},
  St {name="Alena", surname="Shevcova", sex='f', day=30, month=2, year=1993, group=334, iq=106},
  St {name="Fedor", surname="Volkov", sex='m', day=30, month=3, year=1993, group=333, iq=107},
  St {name="Konstantin", surname="Jablochkin", sex='m', day=9, month=1, year=1990, group=334, iq=109},
  St {name="Aleksej", surname="Okunev", sex='m', day=31, month=12, year=1991, group=334, iq=107},
  St {name="Tat'jana", surname="Poilenkova", sex='f', day=31, month=7, year=1991, group=334, iq=101},
  St {name="Ol'ga", surname="Pakuljak", sex='f', day=31, month=3, year=1991, group=333, iq=108},
  St {name="Jelina", surname="Imasheva", sex='f', day=31, month=5, year=1993, group=333, iq=108},
  St {name="Aleksej", surname="Gronskij", sex='m', day=30, month=7, year=1989, group=332, iq=109},
  St {name="Marija", surname="Grebenkina", sex='f', day=31, month=12, year=1991, group=332, iq=106}
  ] :: [Student]

french = [("Maksim", "Churkin"), ("Vera", "Aminova"), ("Dar'ja", "Grekova"),
              ("Ivan", "Demkovich"), ("Denis", "Dublenyh"), ("Aleksej", "Korolev"),
              ("Dmitrij", "Zonin"), ("Dmitrij", "Karpov"), ("Vadim", "Shakuro"),
              ("Kirill", "Kornjuhin"), ("Aleksandr", "Chegodaev"), ("Pavel", "Skripnichenko"),
              ("Denis", "Jadarinkin"), ("Vera", "Aminova"), ("Ksenija", "Afonenko"),
              ("Marija", "Kolmogorova"), ("Oleg", "Mihajlov"), ("Ivan", "Kadochnikov"),
              ("Elena", "Lysenko"), ("Anton", "Putrik"), ("Il'ja", "Otradnikov"),
              ("Anna", "Ustavshhikova"), ("Sergej", "Zajkov"), ("Julija", "Burkova"),
              ("Elena", "Mihajlova"), ("Adel'", "Auhatova"), ("Diana", "Taratuhina"),
              ("Rostislav", "Devjatov"), ("Anton", "Vasil'ev"), ("Elena", "Tret'jak"),
              ("Vladimir", "Bataev"), ("Fedor", "Pahomov"), ("Igor'", "Mahlin"),
              ("Ivan", "Kozlov"), ("Anton", "Fonarev"), ("Jakov", "Dlugach"),
              ("Igor'", "Turkin"), ("Dmitrij", "Alekseev"), ("Pavel", "Jushhenko"),
              ("Ivan", "Dudinov"), ("Anton", "Lupanov"), ("Ivan", "Puzyrevskij"),
              ("Leonid", "Andrievskij"), ("Aleksandr", "Korchagin"), ("Kirill", "Zhalnin"),
              ("Anton", "Bobkov"), ("Vladimir", "Tkachev"), ("Danila", "Potapov"),
              ("Denis", "Lisov"), ("Ivan", "Bogatyj"), ("Aleksej", "Kricin"),
              ("Andrej", "Kotov"), ("Kirill", "Znamenskij"), ("Vladimir", "Lesnichenko"),
              ("Il'ja", "Smirnov"), ("Aleksandr", "Kolesnikov"), ("Nikolaj", "Pechenkin"),
              ("Alena", "Shevcova"), ("Konstantin", "Jablochkin"), ("Tat'jana", "Poilenkova"),
              ("Marija", "Grebenkina")] :: [(String, String)]
              
discrete_mathematics = [("Elizaveta", "Anohina"), ("Denis", "Dublenyh"), ("Aleksej", "Korolev"),
                            ("Vjacheslav", "Shaprynskij"), ("Dmitrij", "Karpov"), ("Sergej", "Larjushkin"),
                            ("Aleksandr", "Toporov"), ("Daniil", "Ajzenshtejn"), ("Vera", "Aminova"),
                            ("Ksenija", "Afonenko"), ("Dmitrij", "Zonin"), ("Marija", "Kolmogorova"),
                            ("Aleksej", "Korolev"), ("Aleksej", "Kutyrev"), ("Il'ja", "Otradnikov"),
                            ("Anna", "Ustavshhikova"), ("Nadezhda", "Skachkova"), ("Vladimir", "Telichkin"),
                            ("Ivan", "Turmyshev"), ("Evgenij", "Kuznecov"), ("Sergej", "Zajkov"),
                            ("Julija", "Burkova"), ("Jurij", "Starovojtov"), ("Jakov", "Mozgoev"),
                            ("Elena", "Mihajlova"), ("Sergej", "Toropkin"), ("Igor'", "Gulamov"),
                            ("Vladimir", "Bataev"), ("Igor'", "Mahlin"), ("Ivan", "Kozlov"),
                            ("Andrej", "Kolosov"), ("Marina", "Stepanova"), ("Matvej", "Kornilov"),
                            ("Jakov", "Dlugach"), ("Igor'", "Turkin"), ("Oleg", "Samojlenko"),
                            ("Viktor", "Chernyshov"), ("Anton", "Lupanov"), ("Aleksandr", "Roshhupkin"),
                            ("Aleksandr", "Korchagin"), ("Kirill", "Zhalnin"), ("Anton", "Bobkov"),
                            ("Konstantin", "Novikov"), ("Ivan", "Kondrashov"), ("Danila", "Potapov"),
                            ("Denis", "Lisov"), ("Marija", "Felicina"), ("Andrej", "Vikulov"),
                            ("Artem", "Kuharenko"), ("Sergej", "Anohovskij"), ("Aleksandr", "Zaharov"),
                            ("Andrej", "Kotov"), ("Vladimir", "Lesnichenko"), ("Il'ja", "Smirnov"),
                            ("Aleksandr", "Kolesnikov"), ("Nikolaj", "Pechenkin"), ("Alena", "Shevcova"),
                            ("Tat'jana", "Poilenkova"), ("Ol'ga", "Pakuljak"), ("Jelina", "Imasheva"),
                            ("Aleksej", "Gronskij"), ("Marija", "Grebenkina")] :: [(String, String)]

programming = [("Dar'ja", "Grekova"), ("Ivan", "Demkovich"), ("Denis", "Dublenyh"),
                   ("Aleksej", "Korolev"), ("Vladislav", "Isenbaev"), ("Dmitrij", "Zonin"),
                   ("Aleksandr", "Golubev"), ("Vadim", "Shakuro"), ("Kirill", "Kornjuhin"),
                   ("Anton", "Putrik"), ("Maksim", "Putrik"), ("Aleksandr", "Chegodaev"),
                   ("Vera", "Aminova"), ("Ksenija", "Afonenko"), ("Marija", "Kolmogorova"),
                   ("Viktor", "Samun'"), ("Oleg", "Mihajlov"), ("Aleksej", "Korolev"),
                   ("Il'ja", "Otradnikov"), ("Anna", "Ustavshhikova"), ("Ivan", "Turmyshev"),
                   ("Evgenij", "Kuznecov"), ("Julija", "Burkova"), ("Jakov", "Mozgoev"),
                   ("Egor", "Ignat'ev"), ("Tat'jana", "Eliseeva"), ("Adel'", "Auhatova"),
                   ("Rostislav", "Devjatov"), ("Anton", "Vasil'ev"), ("Elena", "Tret'jak"),
                   ("Fedor", "Pahomov"), ("Viktor", "Aljushin"), ("Ivan", "Kozlov"),
                   ("Vadim", "Avdeev"), ("Anton", "Fonarev"), ("Ekaterina", "Sambukova"),
                   ("Dmitrij", "Alekseev"), ("Viktor", "Chernyshov"), ("Ivan", "Puzyrevskij"),
                   ("Aleksandr", "Petrov"), ("Aleksandr", "Roshhupkin"), ("Aleksandr", "Korchagin"),
                   ("Anton", "Bobkov"), ("Konstantin", "Novikov"), ("Vladimir", "Tkachev"),
                   ("Ivan", "Kondrashov"), ("Danila", "Potapov"), ("Aleksej", "Davydov"),
                   ("Denis", "Lisov"), ("Marija", "Felicina"), ("Andrej", "Vikulov"),
                   ("Aleksej", "Kricin"), ("Artem", "Kuharenko"), ("Aleksandr", "Zaharov"),
                   ("Il'ja", "Smirnov"), ("Ignat", "Kolesnichenko"), ("Tat'jana", "Poilenkova"),
                   ("Ol'ga", "Pakuljak"), ("Aleksej", "Gronskij"), ("Marija", "Grebenkina")] :: [(String, String)]

				   
get_name (St name surname sex day month year group iq) = name